name: Upload Static Site to AWS S3
on:
  push:
    branches:
      - main
      - 'swp-generator/**'
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./swp-generator
      build-directory: ./swp-generator/cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: go mod verify
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: go build -o ../../bin/swpgenerator
        working-directory: ${{ env.build-directory }}

      - name: Generate static site
        run: ./bin/swpgenerator

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./web/ s3://${{ secrets.S3_BUCKET_NAME }} --delete